<footer class="pied_page">

    <p class="tous_droits">Tous droits réservés © 2016 GSB</p>

</footer>

<style>

    /*Pied de page (Tous droits réservés)*/
    .pied_page
    {
        /*border: 1px #333333 solid;*/
        position: absolute;
        bottom: 0px;
        width: 100%;
        height: 3%;
        background-color: #333333;

    }

    /*Pied de page (Tous droits réservés)*/
    .tous_droits
    {
        /*border: 1px blue solid;*/
        margin: 0px;
        font-family: Verdana;
        font-size: 16px;
        color: white;
        height: 100%;
        width: 15%;
        margin-left: 40%;
        line-height: 25px;
    }
</style>